# Generated by Django 4.2.6 on 2023-10-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="button_text",
            field=models.CharField(blank=True, default="Book", max_length=50),
        ),
    ]
