# Generated by Django 4.2.6 on 2023-10-31 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_eventpage_button_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="event_type_list",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_type",
                to="events.eventtype",
            ),
        ),
    ]
