# Generated by Django 4.2.6 on 2023-10-31 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_remove_eventpage_event_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventpage",
            old_name="event_type_list",
            new_name="event_type",
        ),
    ]
