# Generated by Django 4.2.6 on 2023-11-01 03:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_rename_event_type_list_eventpage_event_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpage",
            name="event_type",
        ),
    ]
