version: '3.9'

services:
  nginx:
    build: ./nginx
    container_name: connect4-wagtail-nginx
    restart: unless-stopped
    depends_on:
      - wagtail

    ports:
      - 8014:80
    volumes:
      - ./static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media

  wagtail:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: connect4-wagtail
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./.env
    expose:
      - 8000
    command : wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000
    #command : wait-for-it.sh db:5432 -- gunicorn website.wsgi:application -w 2 --threads=4 --worker-class=gthread --bind 0.0.0.0:8000 --timeout 120
    volumes:
      - .:/app/:consistent
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh

  db:
    image: postgres:15.2
    restart: unless-stopped
    container_name: connect4-wagtail-db
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
