# Generated by Django 4.2.6 on 2023-10-24 22:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0002_partnerlistingpage_partnerpage_delete_partner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partnerpage",
            name="button_text",
        ),
    ]
