# Generated by Django 4.2.5 on 2023-09-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("singleline", "Single line text"),
                    ("multiline", "Multi-line text"),
                    ("email", "Email"),
                    ("url", "URL"),
                ],
                max_length=16,
                verbose_name="Field Type",
            ),
        ),
    ]
