# Generated by Django 4.2.7 on 2023-11-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_alter_formfield_field_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactpage",
            name="map_url",
            field=models.URLField(
                blank=True,
                help_text="Optional. If you provide a link here the map image will become a link.",
            ),
        ),
    ]
