# Generated by Django 4.2.6 on 2023-10-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registration",
            "0002_familymember_created_at_familymember_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="childmore",
            name="school",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="School"
            ),
        ),
    ]
