# Generated by Django 4.2.6 on 2023-10-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0003_alter_childmore_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childmore",
            name="fsm",
            field=models.CharField(
                choices=[("1", "Yes"), ("0", "No"), ("-1", "-")],
                default=-1,
                verbose_name="Free School Meal?",
            ),
        ),
        migrations.AlterField(
            model_name="childmore",
            name="sen_detail",
            field=models.TextField(
                blank=True, max_length=1024, null=True, verbose_name="SEN Details"
            ),
        ),
    ]
