# Generated by Django 4.2.6 on 2023-10-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0004_alter_childmore_fsm_alter_childmore_sen_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childmore",
            name="fsm",
            field=models.CharField(
                choices=[("1", "Yes"), ("0", "No"), ("-1", "-")],
                default="-1",
                verbose_name="Eligible for benefit related Free School Meals (FSM)?",
            ),
        ),
    ]
