# Generated by Django 4.2.6 on 2023-10-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0005_alter_childmore_fsm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childmore",
            name="fsm",
            field=models.CharField(
                choices=[("1", "Yes"), ("0", "No"), ("None", "-")],
                default="None",
                verbose_name="Eligible for benefit related Free School Meals (FSM)?",
            ),
        ),
        migrations.AlterField(
            model_name="childmore",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Female", "Female"),
                    ("Male", "Male"),
                    ("Other", "Other"),
                    ("Unanswered", "Prefer not to say"),
                ],
                default="Unanswered",
                max_length=10,
                verbose_name="Gender",
            ),
        ),
    ]
