# Generated by Django 4.2.6 on 2023-10-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0007_alter_childmore_sen_req"),
    ]

    operations = [
        migrations.AddField(
            model_name="childmore",
            name="sen_new",
            field=models.CharField(
                choices=[("1", "Yes"), ("0", "No"), ("None", "-")],
                default="None",
                verbose_name="Special educational needs (SEN) or Education health care plan (EHCP)?",
            ),
        ),
    ]
