# Generated by Django 4.2.6 on 2023-10-31 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0008_childmore_sen_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="childmore",
            name="sen_req",
        ),
    ]
