# Generated by Django 4.2.6 on 2023-10-31 22:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0009_remove_childmore_sen_req"),
    ]

    operations = [
        migrations.RenameField(
            model_name="childmore",
            old_name="sen_new",
            new_name="sen_req",
        ),
    ]
