# Generated by Django 4.2.6 on 2023-10-31 23:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0011_childmore_sen_req_boolean"),
    ]

    operations = [
        migrations.RenameField(
            model_name="childmore",
            old_name="sen_req_boolean",
            new_name="fsm_boolean",
        ),
    ]
