# Generated by Django 4.2.6 on 2023-10-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0012_rename_sen_req_boolean_childmore_fsm_boolean"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="childmore",
            name="fsm",
        ),
        migrations.AlterField(
            model_name="childmore",
            name="fsm_boolean",
            field=models.BooleanField(
                verbose_name="Eligible for benefit related Free School Meals (FSM)?"
            ),
        ),
    ]
