# Generated by Django 4.2.6 on 2023-11-01 02:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0014_rename_fsm_boolean_childmore_fsm"),
    ]

    operations = [
        migrations.RenameField(
            model_name="childmore",
            old_name="fsm",
            new_name="fsm_boolean",
        ),
    ]
