# Generated by Django 4.2.6 on 2023-11-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0015_rename_fsm_childmore_fsm_boolean"),
    ]

    operations = [
        migrations.AddField(
            model_name="childmore",
            name="fsm",
            field=models.CharField(
                choices=[("1", "Yes"), ("0", "No"), ("None", "-")],
                default="None",
                verbose_name="Eligible for benefit related Free School Meals (FSM)?",
            ),
        ),
    ]
