# Generated by Django 4.2.6 on 2023-11-01 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0016_childmore_fsm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="childmore",
            name="fsm_boolean",
        ),
    ]
