# Generated by Django 4.2.6 on 2023-11-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0017_remove_childmore_fsm_boolean"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="childmore",
            name="fsm",
        ),
        migrations.AddField(
            model_name="childmore",
            name="fsm_char",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("None", "-")],
                default="None",
                verbose_name="Eligible for benefit related Free School Meals (FSM)?",
            ),
        ),
        migrations.AlterField(
            model_name="childmore",
            name="sen_req",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("None", "-")],
                default="None",
                verbose_name="Special educational needs (SEN) or Education health care plan (EHCP)?",
            ),
        ),
    ]
