# Generated by Django 4.2.6 on 2023-11-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0018_remove_childmore_fsm_childmore_fsm_char_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="childmore",
            name="fsm_char",
        ),
        migrations.AddField(
            model_name="childmore",
            name="fsm",
            field=models.BooleanField(
                null=True,
                verbose_name="Eligible for benefit related Free School Meals (FSM)?",
            ),
        ),
    ]
