# Generated by Django 4.2.7 on 2023-11-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0022_rename_sen_req_new_childmore_sen_req"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childmore",
            name="sen_detail",
            field=models.TextField(
                blank=True, max_length=1024, null=True, verbose_name="SEN/EHCP Details"
            ),
        ),
        migrations.AlterField(
            model_name="childmore",
            name="sen_req",
            field=models.BooleanField(
                null=True,
                verbose_name="Special educational needs (SEN) or Education Health Care Plan (EHCP)?",
            ),
        ),
    ]
