# Generated by Django 4.2.7 on 2023-11-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0023_alter_childmore_sen_detail_alter_childmore_sen_req"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childmore",
            name="fsm",
            field=models.BooleanField(
                null=True, verbose_name="In receipt of Free School Meals (FSM)?"
            ),
        ),
    ]
