# Generated by Django 4.2.5 on 2023-09-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialMediaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, help_text="Enter your Facebook URL"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, help_text="Enter your Twitter URL"),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, help_text="Enter your Instagram URL"),
                ),
                (
                    "youtube",
                    models.URLField(blank=True, help_text="Enter your YouTube URL"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
