# Generated by Django 4.2.6 on 2023-10-24 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "registration",
            "0002_familymember_created_at_familymember_updated_at_and_more",
        ),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("booking", "family_member")},
        ),
    ]
