# Generated by Django 4.2.5 on 2023-10-03 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='additional_information',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Additional information'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Town/City'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Contact mobile phone'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='family_name',
            field=models.CharField(default='Please provide a name for the family.', max_length=70, verbose_name='Family Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo_consent',
            field=models.BooleanField(default=False, verbose_name='Photo consent?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Post Code'),
        ),
    ]
