# Generated by Django 4.2.5 on 2023-10-03 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='additional_information',
            field=models.CharField(blank=True, help_text='e.g. Family is sensitive to bright light.', max_length=4096, null=True, verbose_name='Additional information'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, help_text='e.g. Havant', max_length=50, null=True, verbose_name='Town/City'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, help_text='e.g. +612392489800', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Contact mobile phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='family_name',
            field=models.CharField(default='Please provide a name for the family.', help_text='e.g. The Addams Family', max_length=70, verbose_name='Family Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo_consent',
            field=models.BooleanField(default=False, help_text='Allow photos to be taken of anyone in the family? These may be used, for e.g., in Connect4 publicity or PCS newsletters.', verbose_name='Photo consent?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_code',
            field=models.CharField(blank=True, help_text='e.g. PO9 4BU', max_length=12, null=True, verbose_name='Post Code'),
        ),
    ]
