# Generated by Django 4.2.7 on 2023-11-22 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0003_alter_customuser_additional_information_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="additional_information",
            field=models.CharField(
                blank=True,
                help_text="Any useful information for Connect4 staff to know about your family as a whole, e.g. Family is sensitive to bright light.",
                max_length=4096,
                null=True,
                verbose_name="Additional information",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="contact_number",
            field=models.CharField(
                blank=True,
                help_text="Enter a valid international mobile phone number starting with +(country code), e.g. +4423924898",
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid international mobile phone number starting with +(country code)",
                        regex="^\\+(?:[0-9]●?){6,14}[0-9]$",
                    )
                ],
                verbose_name="Contact mobile phone",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="family_name",
            field=models.CharField(
                default="Please provide a name for the family.",
                help_text="This is a descriptive name for the family for display and sorting purposes only e.g. Addams Family",
                max_length=70,
                verbose_name="Family Name",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="photo_consent",
            field=models.BooleanField(
                default=False,
                help_text="Please tick if you allow photos to be taken of anyone in the family. These may be used, for e.g., in Connect4 publicity or PCS newsletters.",
                verbose_name="Photo consent?",
            ),
        ),
    ]
